server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  server:
    git:
  application:
    name: config-service
  cloud:
    config:
      uri: https://github.com/yeahokthen/config-repo.git
      server:
        git:
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true




